//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RachelBarnesMobileDevelopment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costs
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Selling_Price { get; set; }
        public string Selling_Weight { get; set; }
        public decimal Selling_Weight_Ounces { get; set; }
        public int Count_Ingredient_Recorded_In_Costs { get; set; }
        public decimal Average_Price { get; set; }
    }
}
