//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RachelBarnesMobileDevelopment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RachelsRosesMobileDevelopmentEntities : DbContext
    {
        public RachelsRosesMobileDevelopmentEntities()
            : base("name=RachelsRosesMobileDevelopmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ingredients> Ingredients { get; set; }
        public virtual DbSet<Pantry> Pantry { get; set; }
        public virtual DbSet<IngredientConsumption> IngredientConsumption { get; set; }
        public virtual DbSet<Costs> Costs { get; set; }
        public virtual DbSet<SellingInformation> SellingInformation { get; set; }
        public virtual DbSet<Recipes> Recipes { get; set; }
        public virtual DbSet<IngredientDensities> IngredientDensities { get; set; }
    }
}
