//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RachelBarnesMobileDevelopment
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientSellingData
    {
        public int ingredient_id { get; set; }
        public string name { get; set; }
        public string walmart_name { get; set; }
        public Nullable<int> walmart_item_id { get; set; }
        public string selling_weight { get; set; }
        public Nullable<decimal> selling_price { get; set; }
        public Nullable<int> sold_in_packs { get; set; }
    }
}
