//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RachelBarnesMobileDevelopment
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientConsumptionData
    {
        public int ingredient_id { get; set; }
        public string measurement { get; set; }
        public string name { get; set; }
        public Nullable<decimal> ounces_consumed { get; set; }
        public Nullable<decimal> ounces_remaining_at_time_of_use { get; set; }
    }
}
