//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RachelBarnesMobileDevelopment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredients
    {
        public int Id { get; set; }
        public Nullable<int> Recipe_Id { get; set; }
        public string Name { get; set; }
        public string Measurement { get; set; }
        public string Type { get; set; }
        public string Classification { get; set; }
        public string Selling_Weight { get; set; }
    }
}
