//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RachelBarnesMobileDevelopment
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyPantry
    {
        public string name { get; set; }
        public string walmart_name { get; set; }
        public Nullable<int> walmart_item_id { get; set; }
        public Nullable<decimal> ounces_consumed_of_product { get; set; }
        public Nullable<decimal> ounces_remaining_of_product { get; set; }
        public System.DateTime expiration_date { get; set; }
        public int refill_needed { get; set; }
    }
}
