//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RachelBarnesMobileDevelopment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pantry
    {
        public int Pantry_Id { get; set; }
        public string Name { get; set; }
        public decimal Ounces_Consumed { get; set; }
        public decimal Ounces_Remaining { get; set; }
        public int Expired { get; set; }
        public int Expiring_Soon { get; set; }
    }
}
