//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RachelBarnesMobileDevelopment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        public int recipe_id { get; set; }
        public string name { get; set; }
        public int yield { get; set; }
        public decimal aggregated_price { get; set; }
        public decimal price_per_serving { get; set; }
        public int no_of_ingredients { get; set; }
    }
}
